# Generated by Django 4.2.1 on 2023-06-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='image_url',
        ),
    ]
